spring:
  #   dev
  #   mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-uf684wnt4zxp6va1zxo.mysql.rds.aliyuncs.com:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123qwe!@#QWE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#    log
logging:
  level:
    root: info
    com.takr: debug
  file:
    name: log/blog-dev.log
